enum Country { ... }

enum RequestStatus {            # Статус запроса на добавление текущий версии тур. продукта
   WAITING                      # ОЖИДАНИЕ
   REVISION                     # ОТПРАВЛЕНО НА ДОРАБОТКУ
   ACCEPTED                     # ПРИНЯТО
}

enum RequestResourceStatus {    # Статус запроса на добавление тур. продукта
   WAITING                      # ОЖИДАНИЕ
   REJECTED                     # ОТКЛОНЕНО
   ACCEPTED                     # ПРИНЯТО
}

enum ResourceStatus {           # Статус объекта (ресурса)
    ACTIVE                      # АКТИВНО
    INACTIVE                    # НЕАКТИВНО
}

enum EventStatus {              # Статус мероприятия
    SCHEDULED                   # ЗАПЛАНИРОВАНО
    CANCELLED                   # ОТМЕНЕНО
    CONDUCTED                   # ПРОВЕДЕНО
}

scalar DateTime                 # Дата и время
scalar Interval                 # Интервал между точками времени
scalar Duration                 # Временная продолжительность

scalar Passport                 # Паспортные данные (серия и номер) [доп. фото и др. данные]
scalar Phone                    # Номер контактного телефона
scalar Email                    # Адрес электронной почты

type Attachment {               # Вложение
    id: ID!
    url: String!                # Ссылка на вложение
    filename: String            # Имя файла вложения
    mimetype: String!           # Тип файла вложения
    size: Integer!              # Размер файла вложения
    author: User!               # Автор загрузки вложения
}

type AddressElement {           # Элемент адреса
    type: String!               # Вид/Тип
    designation: String!        # Наименование/Номер
}

type Address {                  # Адрес
    country: Country!           # Страна (наименование)
    subject: String!            # Субъект (наименование)
    district: String!           # Городской округ (наименование)
    locality: AddressElement!   # Населенный пункт (вид, наименование)
    street: AddressElement!     # Элемент улично-дорожной сети (вид, наименование)
    building: AddressElement!   # Здание/сооружение (тип, номер)
    additional: AddressElement  # Здание/сооружение [доп.] (тип, номер)
    apartament: Integer         # Номер квартири/офиса [доп.]
}

type GeoLocation {              # Геопозиция
    latitude: Float!            # Широта
    longitude: Float!           # Долгота
}

type Contact {                  # Контакные данные
    address: Address            # Адрес
    location: GeoLocation       # Геопозиция (для карты)
    passport: Passport          # Паспортные данные
    phone: Phone                # Номер контактного телефона
    email: Email                # Адрес электронной почты
}

# Администратор                 # Admin    (!)
# Разработчик                   # Developer(!)
# Владелец                      # Owner    (!)
# Клиент                        # Client   (!)
# Никто                         # NoBody   (ø)
# Пользователь                  # User     (Admin | Developer | Owner | Client)
# Все                           # Everyone (AnyBody | NoBody)

interface User {                # Пользователь
    id: ID!
    created_at: DateTime!
    contact: Contact!           # Контактные данные
    # Do need extra fields?
}

type Admin implements User {    # Администратор
    id: ID!
    created_at: DateTime!
    contact: Contact!           # Контактные данные
    # Do need extra fields?
}

type Developer implements User {# Разработчик
    id: ID!
    created_at: DateTime!
    contact: Contact!           # Контактные данные
    # Need extra?
    rating: Rating!             # Рейтинг
}

type Owner implements User {    # Владелец
    id: ID!
    created_at: DateTime!
    lastname: String!           # Фамилия
    middlename: String!         # Отчество
    firstname: String!          # Имя
    fullname: String!           # Полное ФИО
    contact: Contact!           # Контактные данные
    sites: [TouristSite!]!      # Туристические точки (ресурсы)
    routes: [TouristRoute!]!    # Туристические маршруты (продукты)
    rating: Rating!             # Рейтинг
}

type Client implements User {   # Клиент
    id: ID!
    created_at: DateTime!
    contact: Contact!           # Контактные данные
    lastname: String            # Фамилия
    middlename: String          # Отчество
    firstname: String           # Имя
    fullname: String            # Полное ФИО
    birthday: Date              # Дата рождения
}

type Guide implements User {    # Экскурсовод
    id: ID!
    lastname: String!           # Фамилия
    middlename: String!         # Отчество
    firstname: String!          # Имя
    fullname: String!           # Полное ФИО
    contact: Contact!           # Контактные данные
    rating: Rating!             # Рейтинг
}

type Rating {                   # Рейтинг
    reviews: [Review!]!         # Отзывы
    score: Float!               # Оценка
}

type Review {                   # Отзыв
    id: ID!
    created_at: DateTime!
    score: Float!               # Оценка
    title: String               # Заголовок
    content: String             # Контент (отзыв)
    author: User!               # Автор отзыва
    timestamp: DateTime         # Дата и время
    attachments: [Attachment!]! # Вложения (фото, видео)
    usefulness: Usefulness!     # Оценка комментария (полезность)
    edited_at: DateTime         # Временная метка "ИЗМЕНЕННО" (отредактировано)
}

type Usefulness {               # Оценка комментария (полезность)
    like: Integer!              # Кол-во отметок "ЗА"
    dislike: Integer!           # Кол-во отметок "ПРОТИВ"
}

type Comment {                  # Комментарий
    id: ID!
    created_at: DateTime!
    author: User!               # Автор комментария
    content: String!            # Контент (комментарий)
    reply: [Comment!]!          # Ответы (комментарие)
    usefulness: Integer!        # Кол-во отметок "ПОЛЕЗНО"
    edited_at: DateTime         # Временная метка "ИЗМЕНЕННО" (отредактировано)
}

type WorkingHours {             # Время работы
    opening: Time!              # Время открытия
    closing: Time!              # Время закрытия
}

type WorkingDays {              # Даты работы [для временных «событий»]
    start: Date!                # Дата начала
    end: Date!                  # Дата окончания
}

type TouristSite {              # Туристический объект (ресурс)
    id: ID!
    owner: Owner!               # Владелец                              !DEPRECATED::reason:заменить?!
    name: String!               # Наименование
    description: String         # Описание
    contact: Contact!           # Контактные данные
    wokringhours: WorkingHours  # Часы работы                           !DEPRECATED::reason:заменить?!
    wokringdays: WorkingDays    # Временный период (Дата проведения)    !DEPRECATED::reason:заменить?!
    attachments: [Attachment!]! # Вложения (фото, видео)
    duration: Duration          # Длительность
    rating: Rating!             # Рейтинг
    status: ResourceStatus!     # Статус объекта (ресурса)
}

type TouristRoute {             # Туристический маршрут (ресурс)
    id: ID!
    name: String!               # Наименование
    description: String         # Описание
    developer: Developer!       # Разработчик                           !DEPRECATED::reason:заменить?!
    contact: Contact!           # Контактные данные
    wokringhours: WorkingHours  # Часы работы                           !DEPRECATED::reason:заменить?!
    wokringdays: WorkingDays    # Временный период (Дата проведения)    !DEPRECATED::reason:заменить?!
    sites: [TouristSite!]!      # Туристические точки (ресурсы)
    attachments: [Attachment!]! # Вложения (фото, видео)
    distance: Float             # Расстояние (в километрах, с точностью до 3 знаков)
    duration: Duration          # Длительность
    rating: Rating!             # Рейтинг
    marketability: Integer!     # Продаваемость
    status: ResourceStatus!     # Статус маршрута (ресурса)
}

type TouristEvent {             # Туристическое мероприятие (продукт)
    id: ID!
    name: String!               # Наименование
    developer: Developer!       # Разработчик
    route: TouristRoute!        # Туристический маршрут (ресурс)
    guide: Guide!               # Экскурсовод
    wokringhours: WorkingHours! # Часы работы
    wokringdays: WorkingDays!   # Дата начала и окончания мероприятия
    attachments: [Attachment!]! # Вложения (материалы мероприятия)
    comments: [Comment!]!       # Комментарии
    rating: Rating!             # Рейтинг
    price: Integer              # Цена
    seats: Integer              # Количество свободных мест
    status: EventStatus!        # Статус мероприятия
}

union TouristResource = TouristEvent | TouristRoute | TouristSite

type ResourceRequest {          # Запрос
    id: ID!
    resources: [RequestAttachment!]!# История ресурса
    resource: RequestAttachment!# Текущая/последняя версия ресурса
    status: RequestStatus!      # Статус запроса
}

type RequestAttachment {        # Ресурс запроса
    version: Integer!
    resource: TouristResource!  # Прикрепленный ресурс
    status: RequestResourceStatus!# Статус ресурса запроса
    remark: String              # Замечания
}


type Query {

}

type Mutation {

}

schema {
    query: Query
    mutation: Mutation
}